import {
  Globe,
  Users,
  Handshake,
  UsersRound,
  BarChart3,
  TrendingUp,
  Award,
  ShieldCheck,
  Zap,
  HeartHandshake,
  Target,
  Eye,
  HardHat,
  Cog,
  Wheat,
  Shirt,
  ShoppingBag,
  MapPin,
  Mail,
  Phone,
  Linkedin,
  Menu,
  X,
  ChevronDown,
  Settings,
  MailPlus,
  Info,
  Plus,
  Trash2,
  GripVertical,
  ArrowUp,
  ArrowDown,
  Pencil,
  Briefcase,
  Building,
  Building2,
  Store,
  Factory,
  Warehouse,
  Landmark,
  BadgeDollarSign,
  CircleDollarSign,
  CreditCard,
  WalletCards,
  Receipt,
  ChartNoAxesCombined,
  ChartColumn,
  ChartPie,
  Presentation,
  HandCoins,
  Scale,
  FileChartColumn,
  ClipboardCheck,
  Earth,
  Plane,
  Ship,
  Truck,
  Container,
  Package,
  Boxes,
  Navigation,
  Compass,
  Route,
  Map,
  MapPinned,
  LocateFixed,
  Anchor,
  Train,
  Bus,
  Car,
  Wrench,
  Hammer,
  Construction,
  Drill,
  Bolt,
  CircuitBoard,
  Cpu,
  Microchip,
  Cable,
  Gauge,
  Pickaxe,
  Sprout,
  Leaf,
  TreePine,
  Tractor,
  Apple,
  Beef,
  Milk,
  Fish,
  CookingPot,
  Utensils,
  Coffee,
  ShoppingCart,
  Tag,
  Tags,
  PackageOpen,
  BatteryCharging,
  Plug,
  Fuel,
  Flame,
  Sun,
  Wind,
  Droplets,
  Recycle,
  Laptop,
  Monitor,
  Smartphone,
  Server,
  Database,
  Cloud,
  Wifi,
  Network,
  Code,
  Binary,
  Bot,
  RadioTower,
  User,
  UserRound,
  MessagesSquare,
  MessageCircle,
  Send,
  Contact,
  Headset,
  Languages,
  Shield,
  Lock,
  KeyRound,
  BadgeCheck,
  FileCheck,
  ScrollText,
  ExternalLink,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

// Curated icon map. The admin editor writes icon names as strings into the
// JSON content; this map resolves those names to lucide-react components.
// Keeping an explicit allowlist (instead of importing all of lucide) keeps
// the client bundle small and prevents invalid names from rendering nothing.
// Only icons exported by the installed lucide-react are listed here.
const iconMap: Record<string, ComponentType<LucideProps>> = {
  // UI / misc
  Menu,
  X,
  ChevronDown,
  Info,
  Plus,
  Trash2,
  GripVertical,
  ArrowUp,
  ArrowDown,
  Pencil,
  ExternalLink,
  Eye,
  // Business & trade
  Briefcase,
  Building,
  Building2,
  Store,
  Factory,
  Warehouse,
  Landmark,
  BadgeDollarSign,
  CircleDollarSign,
  CreditCard,
  WalletCards,
  Receipt,
  ChartNoAxesCombined,
  ChartColumn,
  ChartPie,
  Presentation,
  HandCoins,
  Scale,
  FileChartColumn,
  ClipboardCheck,
  BarChart3,
  Target,
  TrendingUp,
  Award,
  Handshake,
  HeartHandshake,
  // International & logistics
  Globe,
  Earth,
  Plane,
  Ship,
  Truck,
  Container,
  Package,
  Boxes,
  Navigation,
  Compass,
  Route,
  Map,
  MapPinned,
  LocateFixed,
  Anchor,
  Train,
  Bus,
  Car,
  MapPin,
  // Industry
  Cog,
  Settings,
  Wrench,
  Hammer,
  Construction,
  HardHat,
  Drill,
  Bolt,
  CircuitBoard,
  Cpu,
  Microchip,
  Cable,
  Gauge,
  Pickaxe,
  // Agriculture & food
  Wheat,
  Sprout,
  Leaf,
  TreePine,
  Tractor,
  Apple,
  Beef,
  Milk,
  Fish,
  CookingPot,
  Utensils,
  Coffee,
  // Textile & retail
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Tag,
  Tags,
  PackageOpen,
  // Energy & environment
  Zap,
  BatteryCharging,
  Plug,
  Fuel,
  Flame,
  Sun,
  Wind,
  Droplets,
  Recycle,
  // Technology
  Laptop,
  Monitor,
  Smartphone,
  Server,
  Database,
  Cloud,
  Wifi,
  Network,
  Code,
  Binary,
  Bot,
  RadioTower,
  // People & communication
  User,
  Users,
  UserRound,
  UsersRound,
  MessagesSquare,
  MessageCircle,
  Mail,
  Send,
  Phone,
  Contact,
  Headset,
  Languages,
  // Security & legal
  Shield,
  ShieldCheck,
  Lock,
  KeyRound,
  BadgeCheck,
  FileCheck,
  ScrollText,
  // Email/contact
  MailPlus,
  Linkedin,
};

export const iconNames = Object.keys(iconMap) as IconName[];

export type IconName = keyof typeof iconMap;

export function isValidIconName(name: string): name is IconName {
  return name in iconMap;
}

// Curated categories for the admin icon picker search/filter UX.
export const iconCategories: { label: string; names: IconName[] }[] = [
  {
    label: 'İş',
    names: [
      'Briefcase',
      'Building',
      'Building2',
      'Store',
      'Factory',
      'Warehouse',
      'Landmark',
      'BadgeDollarSign',
      'CircleDollarSign',
      'CreditCard',
      'WalletCards',
      'Receipt',
      'ChartNoAxesCombined',
      'ChartColumn',
      'ChartPie',
      'Presentation',
      'HandCoins',
      'Scale',
      'FileChartColumn',
      'ClipboardCheck',
      'BarChart3',
      'Target',
      'TrendingUp',
      'Award',
      'Handshake',
      'HeartHandshake',
    ],
  },
  {
    label: 'Lojistik',
    names: [
      'Earth',
      'Globe',
      'Plane',
      'Ship',
      'Truck',
      'Container',
      'Package',
      'Boxes',
      'Navigation',
      'Compass',
      'Route',
      'Map',
      'MapPinned',
      'MapPin',
      'LocateFixed',
      'Anchor',
      'Train',
      'Bus',
      'Car',
      'Factory',
      'Warehouse',
    ],
  },
  {
    label: 'Sanayi',
    names: [
      'Cog',
      'Settings',
      'Wrench',
      'Hammer',
      'Construction',
      'HardHat',
      'Drill',
      'Bolt',
      'CircuitBoard',
      'Cpu',
      'Microchip',
      'Cable',
      'Gauge',
      'Pickaxe',
      'Factory',
    ],
  },
  {
    label: 'Tarım & Gıda',
    names: [
      'Wheat',
      'Sprout',
      'Leaf',
      'TreePine',
      'Tractor',
      'Apple',
      'Beef',
      'Milk',
      'Fish',
      'CookingPot',
      'Utensils',
      'Coffee',
    ],
  },
  {
    label: 'Tekstil & Perakende',
    names: [
      'Shirt',
      'ShoppingBag',
      'ShoppingCart',
      'Store',
      'Tag',
      'Tags',
      'PackageOpen',
    ],
  },
  {
    label: 'Enerji & Çevre',
    names: [
      'Zap',
      'BatteryCharging',
      'Plug',
      'Fuel',
      'Flame',
      'Sun',
      'Wind',
      'Droplets',
      'Recycle',
      'Leaf',
    ],
  },
  {
    label: 'Teknoloji',
    names: [
      'Laptop',
      'Monitor',
      'Smartphone',
      'Server',
      'Database',
      'Cloud',
      'Wifi',
      'Network',
      'Code',
      'Binary',
      'Bot',
      'Cpu',
      'CircuitBoard',
      'RadioTower',
    ],
  },
  {
    label: 'İletişim',
    names: [
      'User',
      'Users',
      'UserRound',
      'UsersRound',
      'Handshake',
      'HeartHandshake',
      'MessagesSquare',
      'MessageCircle',
      'Mail',
      'Send',
      'Phone',
      'Contact',
      'Headset',
      'Languages',
    ],
  },
  {
    label: 'Güvenlik & Hukuk',
    names: [
      'Shield',
      'ShieldCheck',
      'Lock',
      'KeyRound',
      'Scale',
      'BadgeCheck',
      'FileCheck',
      'ScrollText',
    ],
  },
  {
    label: 'Diğer',
    names: [
      'Menu',
      'X',
      'ChevronDown',
      'Info',
      'Plus',
      'Trash2',
      'GripVertical',
      'ArrowUp',
      'ArrowDown',
      'Pencil',
      'ExternalLink',
      'Eye',
      'Linkedin',
      'MailPlus',
    ],
  },
];

export function Icon({
  name,
  className,
  ...props
}: { name: string; className?: string } & Omit<LucideProps, 'ref'>) {
  const Cmp = isValidIconName(name) ? iconMap[name] : Globe;
  return <Cmp className={className} {...props} />;
}